// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideNav: typeof import('./../components/asideNav.vue')['default']
    Footer: typeof import('./../components/Layout/Footer/index.vue')['default']
    Header: typeof import('./../components/Layout/Header/index.vue')['default']
    NavBar: typeof import('./../components/Layout/Header/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../components/Layout/SideBar/index.vue')['default']
    SocialList: typeof import('./../components/Layout/SideBar/SocialList.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Waves: typeof import('./../components/Waves/index.vue')['default']
  }
}
